services:
  postgres:
    container_name: postgres_container
    image: postgres:14.1
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dealership
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: pg
    ports:
      - 5434:5432